### ISSUE TITLE
Life_search Does not work with Bootstrap 4.0.0 beta 2

### ISSUE THREAD

**Issue by tobilektri** [heimrichhannot/bootstrap-select#10]
Hey,

I tried to get the "original" Bootstrap-Select working on Bootstrap 4.0.0-beta.2 but it doesn't work. In the Issue you wrote that your repo works with Bootstrap 4, but in my Case the Live-Search does nothing.

Example: https://plnkr.co/edit/zG5BsiiZOukH7KYWgjVZ

Am I doing anything wrong?

Thanks!

**Comment by fatcrobat** [comment]
You must use the `bootstrap.bundle.js` or  `bootstrap.bundle.min.js` that is shipped with `popper.js` which is the new bootstrap dropdown requirement.


Next time please check your console output. :)

```
index.js:21 Uncaught ReferenceError: Popper is not defined
    at index.js:21
(anonymous) @ index.js:21
(index):1 Refused to execute script from 'https://raw.githubusercontent.com/heimrichhannot/bootstrap-select/master/dist/js/bootstrap-select.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):73 Uncaught TypeError: $(...).selectpicker is not a function
    at HTMLDocument.<anonymous> ((index):73)
    at j (jquery.js:3148)
    at Object.fireWith [as resolveWith] (jquery.js:3260)
    at Function.ready (jquery.js:3472)
    at HTMLDocument.J (jquery.js:3503)
```
